### ISSUE TITLE
Incompatible with DocPad v6.80 and above

### ISSUE THREAD

**Issue by cattermo** [docpad/docpad-plugin-nodesass#105]
Plugin requires updating to CoffeeScript v2. This can be done automatically via running https://github.com/bevry/boundation on it.
If you would like the DocPad team to do it, then transfer the repo to the https://github.com/docpad organisation, and run the following:

npm owner add balupton docpad-plugin-assets
npm owner add bevryme docpad-plugin-assets

**Comment by balupton** [comment]
prepped version 2.9.0 however its tests are failing, leaving it up to someone else to figure out
